name: ChitarraTune
options:
  indentWidth: 2
  knownRegions:
    - it
    - en
packages:
  ChitarraTuneCore:
    path: .
targets:
  ChitarraTune macOS:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Apps/Shared
      - path: Apps/macOS
      - path: Apps/Shared/Localization
        type: folder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.picchiarelli.ChitarraTune
        INFOPLIST_FILE: Apps/macOS/Info.plist
        DEVELOPMENT_LANGUAGE: it
        CFBundleDevelopmentRegion: it
    dependencies:
      - package: ChitarraTuneCore
        product: ChitarraTuneCore

schemes:
  ChitarraTune:
    build:
      targets:
        ChitarraTune macOS: [run]
