name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode 15
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.x'
      - name: Generate VersionInfo.swift from Git
        run: |
          set -euo pipefail
          OUT="Apps/Shared/Generated/VersionInfo.swift"
          mkdir -p "$(dirname "$OUT")"
          TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo)"
          SHA="$(git rev-parse --short HEAD 2>/dev/null || echo)"
          DESC="$(git describe --tags --dirty --always 2>/dev/null || git rev-parse --short HEAD 2>/dev/null || echo)"
          DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          cat > "$OUT" <<EOF
          import Foundation
          public enum BuildInfo {
              public static let gitTag: String = "${TAG}"
              public static let gitCommit: String = "${SHA}"
              public static let gitDescribe: String = "${DESC}"
              public static let buildDate: String = "${DATE}"
          }
          EOF
      - name: Resolve Swift Packages
        run: xcodebuild -resolvePackageDependencies -project ChitarraTune.xcodeproj
      - name: SwiftPM tests (Core + Web)
        run: |
          set -euo pipefail
          swift --version
          swift test --parallel --configuration debug --enable-code-coverage
      - name: SwiftPM coverage report
        run: |
          set -euo pipefail
          PROFDATA=$(find .build -name default.profdata | head -n 1 || true)
          if [ -n "$PROFDATA" ]; then
            # Find test bundles built by SwiftPM
            BINS=$(find .build -type f -path "*/debug/*tests.xctest/Contents/MacOS/*" -print | tr '\n' ' ')
            if [ -n "$BINS" ]; then
              xcrun llvm-cov report $BINS -instr-profile "$PROFDATA" | tee coverage.txt
              # Extract TOTAL line percentage if present and print to summary
              PCT=$(awk '/TOTAL/ {print $(NF-1)}' coverage.txt | tail -n1)
              echo "SwiftPM Coverage: ${PCT:-N/A}" >> $GITHUB_STEP_SUMMARY
            fi
          fi
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: swiftpm-coverage
          path: |
            coverage.txt
            .build/**/default.profdata
      - name: Build (Debug)
        run: |
          set -euo pipefail
          xcodebuild -project ChitarraTune.xcodeproj -scheme "ChitarraTune" -configuration Debug -destination 'platform=macOS' -enableCodeCoverage YES build
      - name: UI Tests (Xcode)
        run: |
          set -euo pipefail
          xcodebuild -project ChitarraTune.xcodeproj -scheme "ChitarraTune" -destination 'platform=macOS' -enableCodeCoverage YES test
      - name: Build (Release)
        run: |
          set -euo pipefail
          xcodebuild -project ChitarraTune.xcodeproj -scheme "ChitarraTune" -configuration Release -destination 'platform=macOS' -enableCodeCoverage YES build
