name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode 15
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.x'
      - name: Generate VersionInfo.swift from Git
        run: |
          set -euo pipefail
          OUT="Apps/Shared/Generated/VersionInfo.swift"
          mkdir -p "$(dirname "$OUT")"
          TAG="$(git describe --tags --abbrev=0 2>/dev/null || echo)"
          SHA="$(git rev-parse --short HEAD 2>/dev/null || echo)"
          DESC="$(git describe --tags --dirty --always 2>/dev/null || git rev-parse --short HEAD 2>/dev/null || echo)"
          DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
          cat > "$OUT" <<EOF
          import Foundation
          public enum BuildInfo {
              public static let gitTag: String = "${TAG}"
              public static let gitCommit: String = "${SHA}"
              public static let gitDescribe: String = "${DESC}"
              public static let buildDate: String = "${DATE}"
          }
          EOF
      - name: Build Release
        run: |
          set -euo pipefail
          xcodebuild -project ChitarraTune.xcodeproj -scheme "ChitarraTune" -configuration Release -derivedDataPath build -destination 'platform=macOS' build
          APP="build/Build/Products/Release/ChitarraTune.app"
          test -d "$APP"
          ditto -c -k --sequesterRsrc --keepParent "$APP" ChitarraTune.app.zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ChitarraTune.app.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
