name: SwiftLint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode 15
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.x'
      - name: Install SwiftLint
        run: |
          brew update
          brew install swiftlint
      - name: Run SwiftLint
        run: swiftlint lint --quiet
        continue-on-error: true
